# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_lat', models.FloatField()),
                ('pick_up_long', models.FloatField()),
                ('pick_up_title', models.CharField(max_length=100)),
                ('pick_up_sub_title', models.CharField(max_length=100)),
                ('pick_up_date_time', models.DateTimeField()),
                ('drop_off_lat', models.FloatField()),
                ('drop_off_long', models.FloatField()),
                ('drop_off_title', models.CharField(max_length=100)),
                ('drop_off_sub_title', models.CharField(max_length=100)),
                ('drop_off_date_time', models.DateTimeField()),
                ('repeated_week_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('start_to_pick_up_polyline', models.FileField(blank=True, upload_to='./app/hitches/files/')),
                ('pick_up_to_drop_off_polyline', models.FileField(blank=True, upload_to='./app/hitches/files/')),
                ('drop_off_to_end_polyline', models.FileField(blank=True, upload_to='./app/hitches/files/')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Drive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
