# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitch',
            name='accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
