# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hitch_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitch',
            old_name='repeated_week_days',
            new_name='repeateded_week_days',
        ),
    ]
