# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170301_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitch',
            old_name='repeateded_week_days',
            new_name='repeated_week_days',
        ),
    ]
