# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170305_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='user',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='hitch',
            old_name='user',
            new_name='hitch_hiker',
        ),
        migrations.AlterField(
            model_name='hitch',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitches', to='app.Drive'),
        ),
    ]
