# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170306_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='polyline',
            field=models.BinaryField(),
        ),
    ]
