# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170306_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitch',
            name='adjusted_start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
