# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_hitch_adjusted_start_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitch',
            name='drop_off_to_end_polyline',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='hitch',
            name='pick_up_to_drop_off_polyline',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='hitch',
            name='start_to_pick_up_polyline',
            field=models.BinaryField(),
        ),
    ]
