# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 04:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_long', models.FloatField()),
                ('start_title', models.CharField(max_length=100)),
                ('start_sub_title', models.CharField(max_length=100)),
                ('start_date_time', models.DateTimeField()),
                ('end_lat', models.FloatField()),
                ('end_long', models.FloatField()),
                ('end_title', models.CharField(max_length=100)),
                ('end_sub_title', models.CharField(max_length=100)),
                ('end_date_time', models.DateTimeField()),
                ('max_lat', models.FloatField()),
                ('max_long', models.FloatField()),
                ('min_lat', models.FloatField()),
                ('min_long', models.FloatField()),
                ('repeated_week_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('polyline', models.FileField(blank=True, upload_to='./app/drives/files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='./app/profiles/files/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
