# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('profileImage', models.ImageField(blank=True, upload_to='profile_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
