# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
