# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_long', models.FloatField()),
                ('start_title', models.CharField(max_length=100)),
                ('start_sub_title', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_lat', models.FloatField()),
                ('end_title', models.CharField(max_length=100)),
                ('end_sub_title', models.CharField(max_length=100)),
                ('end_time', models.TimeField()),
                ('repeated_week_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('start_date', models.DateField(blank=True)),
                ('polyline', models.BinaryField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
