# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_drive'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='end_long',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
