# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170225_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
