# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170225_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='polyline',
            field=models.BinaryField(blank=True),
        ),
    ]
