# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170225_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileImage',
            new_name='profile_image',
        ),
    ]
