# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170226_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='../users/files/<built-in function id>'),
        ),
    ]
