# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170227_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='start_time',
        ),
        migrations.AddField(
            model_name='drive',
            name='end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drive',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
