# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170227_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='polyline',
            field=models.FileField(blank=True, upload_to='./app/drives/files/'),
        ),
    ]
